app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from .  import login_manager


class User(UserMixin,db.Model):
    __tablename__ = 'person'
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255), unique=True, index=True)
    username = db.Column(db.String(255))
    secure_password=db.Column(db.String(255))





    @property

    def password(self):
        raise AttributeError('you cannot this attribute password')

    @password.setter


    def password(self,password):
        self.secure_password=generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.secure_password,password)

class pitch(db.Model):
    __tablename__='pitched'
    id = db.Column(db.Integer, primary_key=True)
    pitches=db.Column(db.String(255))


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod


    def get_pitch(cls,id):
        eka=pitch.query.filter_by().all()
        return eka

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

class comments(db.Model):
    __tablename__='comments'
    id =db.Column(db.Integer, primary_key=True)
    pitch_id= db.Column(db.Integer)
    comment=db.Column(db.String(255))



    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_yote(cls,id):
        coke=comments.query.filter_by().all()
        return coke
class votes(db.Model):

    _tablename_="votes"
    id=db.Column(db.Integer,primary_key=True)
    upvotes_id=db.Column(db.Integer)
    downvotes_id=db.Column(db.Integer)


    def save_votes(self):
        db.session.add(self)
        db.session.commit()

    @classmethod

    def get_votes(cls):
        votes=votes.query.filter

app/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from .config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect
login_manager=LoginManager
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

mail=Mail()
csrf = CSRFProtect()
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager=LoginManager()



def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY'] = "EEE"
    app.config['WTF_CSRF_SECRET_KEY'] = "EEE"
    mail.init_app(app)
    db.init_app(app)
    csrf.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)


    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)

from . import views,error

app/main/views.py
from . import main
from flask import render_template,abort
from flask_login import login_required
from ..models import User,pitch
from ..auth.forms import PitchForm



@main.route('/')
def index():
    neew=pitch.get_pitch(id)
    return render_template('home.html',pitch=neew)



@main.route('/user/<jina>',methods=['GET','POST'])
def profile(jina):
    user=User.query.filter_by(username= jina).first()
    if user is None:
        abort(404)
    pitchess = pitch.get_pitch(id)
    return  render_template('profile/profile.html',user=user,lol=pitchess)

app/templates/base.html
{%extends 'bootstrap/base.html' %}

{% block styles%}
    {{super ()}}
   {% include 'navbar.html' %}

{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block content %}

   {{super () }}
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/styles.css')}}">
<body>
<h1  style="text-align:center">AWSOME PITCHES</h1>
<h1>CATEGORIES</h1>
<a href="/pitches" class="badge progress-bar-success">Add Business Pitch</a>
<a href="/travel" class="badge progress-bar-success">Add any other pitch</a>
<h1>ALL PITCHES:</h1>
<h3><li>Petroleum selling company</li></h3>

 <a href="/come" class="badge progress-bar-warning  ">Add comment</a>
</body>

{% for neew in pitch %}
<h3><Li>{{neew.pitches}}</Li></h3>
<a href="/come" class="badge progress-bar-warning  ">Add comment</a>
{% endfor %}





{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Pitches </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                    <a href="{{url_for('main.profile',jina=current_user.username)}}">Profile</a>
                  <li style="color:white;padding:15px;"> Hi, {{current_user.username}}</li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
<!--      -->
            </div>

        </div>
    </div>

app/templates/petroleum.html
{% extends 'base.html' %}
{% block content%}

  {{ super() }}
<h4>Petroleum</h4>

{% endblock %}

app/templates/pitches.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
<div class="row">

<div class="col-md-6">



{{wtf.quick_form(pitchform)}}


</div>
    <div class="col-md-6">



<div class="col-md-6">





</div>

</div>
</div>
</div>


{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}

   {{super () }}
<h2>All  pitches for {{user.username}}</h2>




{% for pitchess in lol %}
<li>{{pitchess.pitches}}</li>
{% endfor %}

{% endblock %}

app/templates/travel.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
<div class="row">

<div class="col-md-6">



{{wtf.quick_form(travelform)}}


</div>
    <div class="col-md-6">



<div class="col-md-6">





</div>

</div>
</div>
</div>


{% endblock%}